### ISSUE TITLE
Warning message appears when quiz result dialog is shown

### ISSUE THREAD

**Issue by darrensapalo** [yusha0123/Quiz-App#1]
## Overview

An error message that says:

```
validateDOMNesting(...): <div> cannot appear as a descendant of <p>
```

inconsistently appears when you complete the quiz.

## Screenshot
![image](https://github.com/yusha0123/Quiz-App/assets/2420577/8c7f5519-4215-4dc5-bfbf-642eb6aa28b5)

## Diagnosis

This is caused by some component `DialogDescription` which internally has a `<p>` tag, which then has a `<div>` as its child element.

![image](https://github.com/yusha0123/Quiz-App/assets/2420577/f7d086c1-9a93-4f2d-81c4-473a169c2380)

## Resolution

Revise the dialog such that `<div>` is not within a `<p>`. This might mean not using `<DialogDescription>` as a parent class, and using it only when you need to display actual text data, and not as a generic element container.

## Other notes

Great work on the project!

**Comment by yusha0123** [comment]
Thanks for finding this error, i will solve it ASAP.
